### ISSUE TITLE
BOR data, ICU and COVID bed occupancy rate at cities level.

### ISSUE THREAD

**Issue by artidataio** [Reynadi531/api-covid19-indonesia-v2#11]
Hi, I'm really thankful for this project. You guys are great. I don't know if it is possible, but I know, this particular data is very useful in analysing the latest situation: https://www.kemkes.go.id/downloads/resources/download/Ketersediaan-Tempat-Tidur-RS-Covid19/BOR-RS-4-AGUSTUS-2021.pdf. The document is updated daily on the following site: https://kemkes.go.id/. But it is in pdf format. Is it possible to convert it to the most suitable  CSV orJSON (preferred)?

**Comment by Reynadi531** [comment]
With the resource right now that i have which is serverless architecture running on vercel with their limited timeout just 10 seconds, i think it would not possible, at least for the infrascructure right now that i have. The timeout already casue many chaos on the API endpoints itself that result error parsing large data. I hope you understand, ill try my best to provide the greatest features, but i dont have any money to buy resources like VPS.

Best regards,
Rey
