### ISSUE TITLE
API nya keren, tapi sdh gak aktif ya?

### ISSUE THREAD

**Issue by kanyezik** [Reynadi531/api-covid19-indonesia-v2#12]
mas, aktifin lg dong APInya
....

**Comment by artidataio** [comment]
Bukan gak aktif, tapi sumber datanya memang ditutup sama pemerintah.

**Comment by Reynadi531** [comment]
API nya bergantung sama server pemerintah, kadang server mereka down, API saya gak ada cache sistemnya, mungkin akan ada cache di v3. Tunggu update selanjutnya
