### ISSUE TITLE
Status code 500 - endpoint /indonesia/harian

### ISSUE THREAD

**Issue by mrrezkii** [Reynadi531/api-covid19-indonesia-v2#13]
Untuk APInya sudah gak bisa di akses lagi ya mas ?
Saya hit di endpoint "indonesia/harian" dapat error 500.
Apa ada alternative lain yang bisa dipakai mas ?

**Comment by Reynadi531** [comment]
Untuk error 500 karena ada maintenece dari server pemerintah, untuk altenatif saya merekomendasikan https://dekontaminasi.com/
