### ISSUE TITLE
[FEATURE] Menambahkan data "last_date" untuk endpoint '/indonesia/provinsi/more'

### ISSUE THREAD

**Issue by mochamadboval3rd** [Reynadi531/api-covid19-indonesia-v2#2]
Hai, sebelumnya terima kasih sudah menciptakan API COVID-19 yang mudah digunakan dan bebas dari masalah CORS. Sesuai judulnya, saya punya permintaan untuk menyertakan juga data **"last_date"** pada endpoint **/indonesia/provinsi/more** mengingat endpoint ini belakangan jarang diperbarui oleh tim Satgas. Tujuannya agar tidak terjadi misinformasi karena total kasus pada endpoint **/indonesia/more** berbeda dengan endpoint **/indonesia/provinsi/more** jika semua dijumlahkan.

Terima kasih :)

**Comment by Reynadi531** [comment]
Hai,

Sebelumnya trimakasih sudah memberikan saran dan masukan. Untuk last_date ada baiknya mau ditempatkan di setiap array provinsi atau diluar ya? Soalnya kalo ditaruh diluar kasian mereka yang pakai map ataupun for loop datanya. Jadi nanti dikasih di setiap array provinsi, gimana?

**Comment by mochamadboval3rd** [comment]
Sebenarnya yang ideal adalah di luar array, jadi hanya ditulis sekali. Namun, saya juga menyadari kalau dilakukan seperti itu maka semua orang yang sebelumnya telah menggunakan API ini harus mengubah kode pemrosesan datanya. Jika menempatkan **last_date** di setiap Array tidak memberatkan Anda di sisi penciptaan API-nya (karena saya tidak tahu proses dibaliknya), maka itu pilihan yang tepat.

**Comment by Reynadi531** [comment]
Saya kasih opsi kalo mau dibikin query sendiri contohnya **/indonesia/provinsi/more?extra_data=last_date** gimana? Atau tetap mau dibikin disetiap array provinsinya?

**Comment by mochamadboval3rd** [comment]
Jika tidak berat di _resource_, sebaiknya ditaruh di setiap Array saja.

**Comment by Reynadi531** [comment]
Sudah saya tambahkan di commit terbaru e85ea84d299cac6bffc714d7a45f9d798ca74999. Silahkan dicoba mas, kalo udah ok, baru saya tutup

**Comment by mochamadboval3rd** [comment]
Saya sudah coba dan berhasil digunakan. Terima kasih sudah mau mempertimbangkan dan menyetujui saran saya. Sukses selalu :)

**Comment by Reynadi531** [comment]
Trimakasih kembali atas saran dan masukkan nya. Salam sukses juga
