### ISSUE TITLE
api/daily is broken 

### ISSUE THREAD

**Issue by refaldodev** [Reynadi531/api-covid19-indonesia-v2#3]
When you hit the daily data server says "An error occurred with this application. /504: GATEWAY_TIMEOUT

**Comment by Reynadi531** [comment]
Halo, trimakasih sudah melaporkan masalah yang terjadi. API yang saya buat merupakan wrapper dari covid19.go.id API. Kemaren, beberapa hari sempat terjadi down pada server covid19.go.id, yang dimana berdampak pada timeout di wrapper yang saya buat. Mohon maaf atas ketidaknyamanannya, sekarang API sudah bisa digunakan kembali. Trimakasih
