### ISSUE TITLE
/indonesia/provinsi/[provinsi-name]

### ISSUE THREAD

**Issue by teknoseries** [Reynadi531/api-covid19-indonesia-v2#4]
Selamat malam mas, bisa Request Issue ga, tambahin lagi url **[/indonesia/provinsi/[provinsi-name]](url)**
soalnya Rest Apinya mas lengkap banget, jadi enak implentasinya apalagi data indonesia. Terima kasih sebelumnya

**Comment by Reynadi531** [comment]
Trimakasih atas sarannya mas, saya akan coba untuk membuat fitur yang mas inginkan, mohon bersabar ya, sekali lagi trimakasih untuk saran dan pendapat nya.

Best regards,
Rey

**Comment by Reynadi531** [comment]
7e3ab28

Sudah saya tambahkan mas, mohon maaf untuk langsung di masukan ke URL terlalu susah, saya menambahkan query ke dalam route nya jadi mas bisa kunjungi [ `/api/indonesia/provinsi?name=dki_jakarta`](https://apicovid19indonesia-v2.vercel.app/api/indonesia/provinsi?name=dki_jakarta) atau [ `/api/indonesia/provinsi/more?name=dki_jakarta`](https://apicovid19indonesia-v2.vercel.app/api/indonesia/provinsi/more?name=dki_jakarta). Query name disesuaikan dengan nama di /api/indonesia/provinsi misalkan `KALIMANTAN TENGAH` dapat di masukan ke query dengan `kalimantan_tengah`. Trimakasih atas saran dan pendapatnya, salam sukses.

Best regards,
Rey
