### ISSUE TITLE
Request for access to the data portal.

### ISSUE THREAD

**Issue by artidataio** [Reynadi531/api-covid19-indonesia-v2#5]
Hi, I would like to let you know that you're doing a great work, especially for a 15 years old. Keep it up and I guarantee that you have a bright future ahead. 

In the meantime, is it possible to request for access to  https://data.covid19.go.id/user/login. I would like to make my own version of covid 19 dashboard. Previously, I have build one through: http://apps.artidata.io/covid-19/. However, I need access to the realtime data to build a more useful one.

Please consider my request to have the login access. Cheers

**Comment by Reynadi531** [comment]
Hi,

First of all thank you for the appreciation of my work. I cant login to the COVID 19 portal itself, i got the data by the open public API endpoint that i got when i visited https://covid19.go.id/peta-sebaran-covid19 and fire up dev tools on chrome browser and i got two most important API endpoints which is https://data.covid19.go.id/public/api/prov.json and https://data.covid19.go.id/public/api/update.json. Then i wrap it with my API so they are more readable, as well as CORS compatible. The data given by the those endpoints are very up to date cause they're used for the main COVID 19 Indonesia government website itself. I hope its answear the question, sorry either myself cant access the data portal, i just use the provided public API endpoints.

Best regards,
Rey
