### ISSUE TITLE
Support for additional data found in https://covid19.go.id/peta-sebaran

### ISSUE THREAD

**Issue by artidataio** [Reynadi531/api-covid19-indonesia-v2#8]
Hi, I found that when the play button on the map is pressed, there is additional data on how each province perform accross time period. As I trace the network call it points to the following link https://data.covid19.go.id/public/api/prov_time.json. Is it possible for you to support this data and enable the CORS as well?

Here is the link to the website that I did on topf of your data: https://observablehq.com/@artidata/covid19-indonesia-watch. I would like to add more, hopefully finding which province is the new hotspot.

**Comment by Reynadi531** [comment]
Have been updated. Please take a look. Thank you
